// ================= 仙途问道 · 凡人修仙传版 全局配置 =================
const CFG = {
  W: 1600, H: 900,
  SURVIVE: 720,                 // 飞升时限（秒）
  WAVE_SEC: 30,

  // ---- 玩家基础 ----
  player: {
    hp: 100, mana: 100,
    speed: 262,
    radius: 20,
    manaRegen: 7,
    hpRegen: 0.25,
    dodge: { cd: 3.0, dist: 230, invuln: 0.34, manaCost: 25, noManaCd: 6.5 },
    critChance: 0.05, critMult: 1.5,
    xpGain: 1.0,
  },

  // ---- 修为（等级）----
  expBase: 14, expPow: 1.0,
  expPerLevel: 2.2,

  // ---- 境界体系（凡人修仙传）----
  // breakType: bolt=天雷劫 | xinsm=碎丹成婴(心魔劫) | ascend=飞升灵界
  realms: [
    { name: '炼气', at: 0,   breakType: null },
    { name: '筑基', at: 8,   breakType: 'bolt', desc: '筑就道基 · 引动小天劫' },
    { name: '结丹', at: 18,  breakType: 'bolt', desc: '凝结金丹 · 金丹雷劫' },
    { name: '元婴', at: 32,  breakType: 'xinsm', desc: '碎丹成婴 · 心魔阻道' },
    { name: '化神', at: 50,  breakType: 'bolt', desc: '元婴出窍 · 化神天劫' },
    { name: '炼虚', at: 68,  breakType: 'ascend', desc: '飞升灵界 · 天地大变' },
    { name: '合体', at: 82,  breakType: 'bolt', desc: '三千年雷劫' },
    { name: '大乘', at: 94,  breakType: 'bolt', desc: '三千年雷劫' },
    { name: '渡劫', at: 105, breakType: 'bolt', desc: '九九重劫' },
    { name: '飞升', at: 999, breakType: null, desc: '功行圆满' },
  ],
  // 渡劫成功后永久加成
  tribBonus: { hp: 55, atkPct: 0.26, speedPct: 0.09, mana: 40 },
  // 三千年雷劫：飞升灵界后每 N 秒一次，威力随次数递增
  millennium: { interval: 180, firstAt: 200 },

  // ---- 装备栏 ----
  slots: 8,   // 八个装备栏（神通槽位），满了不能学新神通

  // ---- 敌人 ----
  enemies: {
    maxCount: 230,
    spawnBase: 0.85,
    spawnMin: 0.24,
    eliteChance: 0.11,
  },
  // 妖兽（OpenMoji 高清兽形 + 妖气光效）
  types: {
    wolf:  { name: '狼妖', sprite: 'wolf',  hp: 24,  speed: 128, dmg: 11, r: 20, xp: 1, score: 1 },
    bee:   { name: '蜂妖', sprite: 'bee',   hp: 13,  speed: 200, dmg: 6,  r: 16, xp: 1, score: 1 },
    golem: { name: '熊妖', sprite: 'bear',  hp: 100, speed: 56,  dmg: 20, r: 26, xp: 3, score: 2 },
    bat:   { name: '蝠妖', sprite: 'bat',   hp: 34,  speed: 90,  dmg: 13, r: 18, xp: 2, score: 2,
             dash: { cd: 3.2, speed: 520, windup: 0.55 },
             ranged: { cd: 4.5, count: 3, speed: 320, range: 620, spread: 0.5, kind: 'dart' } },
    snake: { name: '蛇妖', sprite: 'snake', hp: 48,  speed: 96,  dmg: 9,  r: 20, xp: 3, score: 3,
             ranged: { cd: 2.8, speed: 300, range: 560 } },
    scorpion: { name: '蝎妖', sprite: 'scorpion', hp: 60, speed: 82, dmg: 12, r: 22, xp: 3, score: 3,
             ranged: { cd: 3.6, count: 3, speed: 380, range: 660, spread: 0.35, kind: 'venom' } },
  },
  elite: { sprite: 'fox', name: '狐妖', hpMult: 6, dmgMult: 1.5, rMult: 1.45, xpMult: 8,
           ranged: { cd: 3.0, speed: 260, range: 700, kind: 'willow', dmgMult: 1.2 } },
  boss: {
    wolfking: { name: '虎妖王', sprite: 'tiger', hp: 9000, speed: 130, r: 58, dmg: 24, at: 180,
      skills: { charge: { cd: 5, windup: 0.8, speed: 620 }, summon: { cd: 9, count: 5 },
                burst: { cd: 7, count: 12, speed: 300 } } },
    snake:    { name: '魔蛟', sprite: 'dragon', hp: 32000, speed: 105, r: 64, dmg: 30, at: 360,
      skills: { spray: { cd: 4.5, count: 14, speed: 330 }, slam: { cd: 7, windup: 0.9, speed: 700, range: 170 },
                burst: { cd: 6, count: 16, speed: 340 } } },
    spider:   { name: '噬魂蛛后', sprite: 'spider', hp: 78000, speed: 88, r: 62, dmg: 36, at: 540,
      skills: { web: { cd: 5.5, speed: 260, slow: 0.55, dur: 3.5 }, spawn: { cd: 8, count: 6 },
                burst: { cd: 8, count: 10, speed: 280 }, scatter: { cd: 6, count: 6, speed: 300 } } },
    heart:    { name: '心魔 · 万载妖孽', sprite: 'heart', hp: 240000, speed: 118, r: 70, dmg: 42, at: 690,
      skills: { storm: { cd: 10, bolts: 10 }, mirror: { cd: 14, dur: 5 }, scatter: { cd: 6, count: 24, speed: 300 },
                nova: { cd: 16, count: 28, speed: 230, strong: true }, rain: { cd: 12, drops: 14 } } },
    xinsm:    { name: '心魔 · 元婴劫', sprite: 'heart', hp: 0, speed: 100, r: 60, dmg: 30, at: 0,
      skills: {} },   // 技能由系统动态生成：1:1 复制玩家神通
    jindan:   { name: '金丹 · 结丹大圆满', sprite: 'jindan', hp: 12000, speed: 0, r: 36, dmg: 0, at: 0,
      skills: {} },
  },
  projectile: {
    player: { speed: 720, r: 7, life: 1.4, pierce: 2, enemySpeed: 340, enemyR: 9, enemyLife: 3.5 },
  },

  // ---- 神通（20 个，凡人修仙传体系）----
  // type: active=主动 | passive=被动 | summon=召唤
  // fuse: 与谁融合（双方 Lv5 自动融合）；fusion: 融合产物配置
  skills: {
    sword:   { name: '御剑术', icon: 'icons/swordcraft_flying_sword_attack.png', cat: '剑', type: 'active', max: 5, fuse: 'wave',
      desc: '御使飞剑自动索敌',
      levels: [ { swords: 1, cd: 0.85, dmg: 15, speed: 720 }, { swords: 2, cd: 0.74, dmg: 20, speed: 760 }, { swords: 2, cd: 0.63, dmg: 26, speed: 800 }, { swords: 3, cd: 0.55, dmg: 34, speed: 840 }, { swords: 3, cd: 0.47, dmg: 44, speed: 880 } ],
      gainText: ['飞剑+1', '攻速↑ 伤害↑', '飞剑+1 攻速↑', '攻速↑ 伤害↑'] },
    wave:    { name: '剑气纵横', icon: 'icons/sword_attack.png', cat: '剑', type: 'active', max: 5, fuse: 'sword',
      desc: '环形剑气，穿透群妖',
      levels: [ { cd: 4.2, blades: 12, dmg: 20, speed: 560, life: 0.55 }, { cd: 3.8, blades: 14, dmg: 28, speed: 590, life: 0.6 }, { cd: 3.4, blades: 16, dmg: 38, speed: 620, life: 0.65 }, { cd: 3.0, blades: 18, dmg: 50, speed: 650, life: 0.7 }, { cd: 2.6, blades: 20, dmg: 66, speed: 680, life: 0.75 } ],
      gainText: ['剑气+2', '剑气+2 伤害↑', '剑气+2 伤害↑', '剑气+2 更快'] },
    aura:    { name: '诛仙剑阵', icon: 'icons/sword_defend.png', cat: '剑', type: 'active', max: 5, fuse: 'bamboo',
      desc: '仙剑绕体环护，切伤近敌，格挡妖弹',
      levels: [ { blades: 4, dmg: 17, r: 92, spin: 1.7 }, { blades: 5, dmg: 24, r: 96, spin: 1.8 }, { blades: 6, dmg: 32, r: 100, spin: 1.9 }, { blades: 7, dmg: 42, r: 104, spin: 2.0 }, { blades: 8, dmg: 55, r: 110, spin: 2.2 } ],
      gainText: ['剑+1', '剑+1 伤害↑', '剑+1 伤害↑', '剑+1 更快'] },
    bamboo:  { name: '青竹蜂云剑', icon: 'icons/dart_attack.png', cat: '剑', type: 'active', max: 5, fuse: 'aura',
      desc: '青竹剑光如蜂群攒刺',
      levels: [ { cd: 5.0, count: 8, dmg: 18, spread: 0.5 }, { cd: 4.5, count: 10, dmg: 25, spread: 0.5 }, { cd: 4.0, count: 12, dmg: 33, spread: 0.55 }, { cd: 3.5, count: 14, dmg: 44, spread: 0.55 }, { cd: 3.0, count: 16, dmg: 58, spread: 0.6 } ],
      gainText: ['剑光+2', '剑光+2 伤害↑', '剑光+2 伤害↑', '剑光+2 更快'] },
    spirit:  { name: '剑灵分身', icon: 'icons/scroll.png', cat: '剑', type: 'summon', max: 5, fuse: 'puppet',
      desc: '一气化三清，剑灵同伐',
      levels: [ { count: 1, pct: 0.50, cd: 0.9 }, { count: 2, pct: 0.55, cd: 0.85 }, { count: 3, pct: 0.60, cd: 0.8 }, { count: 4, pct: 0.65, cd: 0.75 }, { count: 5, pct: 0.70, cd: 0.7 } ],
      gainText: ['剑灵+1', '剑灵+1 威力↑', '剑灵+1 威力↑', '剑灵+1 更快'] },
    fire:    { name: '烈焰焚天', icon: 'icons/spellcraft_fire_attack.png', cat: '法', type: 'active', max: 5, fuse: 'thunder',
      desc: '火球轰击妖群最密处',
      levels: [ { cd: 5.2, dmg: 40, r: 105, burn: 7, burnT: 2.4 }, { cd: 4.7, dmg: 56, r: 112, burn: 10, burnT: 2.6 }, { cd: 4.2, dmg: 76, r: 120, burn: 14, burnT: 2.8 }, { cd: 3.7, dmg: 100, r: 128, burn: 19, burnT: 3.0 }, { cd: 3.2, dmg: 132, r: 138, burn: 26, burnT: 3.2 } ],
      gainText: ['伤害↑ 范围↑', '伤害↑ 灼烧↑', '伤害↑ 范围↑', '伤害↑ 更快'] },
    ice:     { name: '冰魄玄光', icon: 'icons/spellcraft_water.png', cat: '法', type: 'active', max: 5, fuse: 'stone',
      desc: '冰锥扇射，冻缓妖物',
      levels: [ { cd: 6.2, shards: 8, dmg: 20, slow: 0.40, slowT: 2.4, speed: 640 }, { cd: 5.6, shards: 10, dmg: 28, slow: 0.45, slowT: 2.7, speed: 660 }, { cd: 5.0, shards: 12, dmg: 38, slow: 0.50, slowT: 3.0, speed: 680 }, { cd: 4.4, shards: 14, dmg: 50, slow: 0.55, slowT: 3.3, speed: 700 }, { cd: 3.8, shards: 16, dmg: 66, slow: 0.60, slowT: 3.6, speed: 720 } ],
      gainText: ['冰锥+2', '冰锥+2 减速↑', '冰锥+2 减速↑', '冰锥+2 更快'] },
    thunder: { name: '天雷引', icon: 'icons/spellcraft_lightning_attack.png', cat: '法', type: 'active', max: 5, fuse: 'fire',
      desc: '九天玄雷，连劈妖邪',
      levels: [ { cd: 5.4, targets: 3, dmg: 34, chain: 2 }, { cd: 4.9, targets: 4, dmg: 47, chain: 2 }, { cd: 4.4, targets: 5, dmg: 64, chain: 3 }, { cd: 3.9, targets: 6, dmg: 86, chain: 3 }, { cd: 3.4, targets: 8, dmg: 116, chain: 4 } ],
      gainText: ['目标+1', '目标+1 伤害↑', '目标+1 连锁↑', '目标+2 伤害↑'] },
    stone:   { name: '千重峰', icon: 'icons/spellcraft_earth_attack.png', cat: '法', type: 'active', max: 5, fuse: 'ice',
      desc: '万仞落石，砸碎妖群',
      levels: [ { cd: 5.5, count: 4, dmg: 30, r: 70 }, { cd: 5.0, count: 5, dmg: 42, r: 76 }, { cd: 4.5, count: 6, dmg: 56, r: 82 }, { cd: 4.0, count: 7, dmg: 74, r: 88 }, { cd: 3.5, count: 8, dmg: 96, r: 95 } ],
      gainText: ['落石+1', '落石+1 伤害↑', '落石+1 伤害↑', '落石+1 更快'] },
    parry:   { name: '乾坤挪移', icon: 'icons/nimble.png', cat: '法', type: 'passive', max: 5, fuse: 'body',
      desc: '受击之际，借力反打',
      levels: [ { chance: 0.25, reflect: 22, dr: 0.03 }, { chance: 0.28, reflect: 34, dr: 0.06 }, { chance: 0.31, reflect: 48, dr: 0.10 }, { chance: 0.34, reflect: 66, dr: 0.14 }, { chance: 0.38, reflect: 88, dr: 0.19 } ],
      gainText: ['反伤↑', '反伤↑ 减伤+3%', '反伤↑ 减伤+4%', '反伤↑ 减伤+5%'] },
    wind:    { name: '御风诀', icon: 'icons/spellcraft_wind_attack.png', cat: '体', type: 'passive', max: 5, fuse: 'blink',
      desc: '身法如风，步履生莲',
      levels: [0.12, 0.24, 0.36, 0.48, 0.60].map(v => ({ speedPct: v })),
      gainText: ['移速 +12%', '移速 +12%', '移速 +12%', '移速 +12%'] },
    body:    { name: '玄金身', icon: 'icons/bodyforge_xinfa.png', cat: '体', type: 'passive', max: 5, fuse: 'parry',
      desc: '淬体如钢，寿元绵长',
      levels: [ { hp: 35, regen: 0.5 }, { hp: 75, regen: 1.1 }, { hp: 120, regen: 1.8 }, { hp: 170, regen: 2.6 }, { hp: 225, regen: 3.5 } ],
      gainText: ['寿元+35 回血↑', '寿元+40 回血↑', '寿元+50 回血↑', '寿元+55 回血↑'] },
    devour:  { name: '噬灵诀', icon: 'icons/vitality_xinfa.png', cat: '体', type: 'passive', max: 5, fuse: 'blood',
      desc: '鲸吞灵气，吸力大增',
      levels: [ { rangePct: 0.25, killHeal: 0.3, xpPct: 0.08 }, { rangePct: 0.55, killHeal: 0.6, xpPct: 0.16 }, { rangePct: 0.90, killHeal: 1.0, xpPct: 0.24 }, { rangePct: 1.30, killHeal: 1.4, xpPct: 0.34 }, { rangePct: 1.75, killHeal: 2.0, xpPct: 0.45 } ],
      gainText: ['吸灵范围↑', '范围↑ 击杀回血', '范围↑ 灵气+8%', '范围↑ 回血↑'] },
    blood:   { name: '血煞功', icon: 'icons/vitality_power_word_attack.png', cat: '体', type: 'passive', max: 5, fuse: 'devour',
      desc: '煞气入体，噬血夺命',
      levels: [ { lifesteal: 0.05, dmgPct: 0.04 }, { lifesteal: 0.08, dmgPct: 0.08 }, { lifesteal: 0.11, dmgPct: 0.12 }, { lifesteal: 0.14, dmgPct: 0.17 }, { lifesteal: 0.18, dmgPct: 0.22 } ],
      gainText: ['吸血+5% 伤害+4%', '吸血+3% 伤害+4%', '吸血+3% 伤害+4%', '吸血+4% 伤害+5%'] },
    blink:   { name: '缩地成寸', icon: 'icons/quick.png', cat: '体', type: 'passive', max: 5, fuse: 'wind',
      desc: '缩地成寸，闪避无双',
      levels: [ { dodgeCd: 0.90, invuln: 0.05, distPct: 0.15 }, { dodgeCd: 0.82, invuln: 0.10, distPct: 0.30 }, { dodgeCd: 0.74, invuln: 0.15, distPct: 0.45 }, { dodgeCd: 0.66, invuln: 0.20, distPct: 0.60 }, { dodgeCd: 0.58, invuln: 0.25, distPct: 0.80 } ],
      gainText: ['冷却-18% 距离+15%', '冷却-8% 无敌+5%', '冷却-8% 距离+15%', '冷却-8% 无敌+5%'] },
    puppet:  { name: '傀儡术', icon: 'icons/talisman.png', cat: '灵', type: 'summon', max: 5, fuse: 'spirit',
      desc: '符箓傀儡，替身挡劫',
      levels: [ { count: 1, hp: 90, dmg: 20 }, { count: 2, hp: 110, dmg: 28 }, { count: 2, hp: 140, dmg: 38 }, { count: 3, hp: 170, dmg: 50 }, { count: 3, hp: 210, dmg: 66 } ],
      gainText: ['傀儡+1', '傀儡+1 强化', '傀儡强化', '傀儡+1 强化'] },
    bugs:    { name: '噬金虫', icon: 'icons/bodyforge_qinna.png', cat: '灵', type: 'summon', max: 5, fuse: 'pill',
      desc: '灵虫噬咬，蚀骨销魂',
      levels: [ { count: 6, dmg: 6, cd: 1.2 }, { count: 8, dmg: 8, cd: 1.1 }, { count: 10, dmg: 11, cd: 1.0 }, { count: 12, dmg: 14, cd: 0.9 }, { count: 14, dmg: 19, cd: 0.8 } ],
      gainText: ['灵虫+2', '灵虫+2 伤害↑', '灵虫+2 伤害↑', '灵虫+2 更快'] },
    pill:    { name: '聚灵丹', icon: 'icons/spellcraft_wood_defend.png', cat: '灵', type: 'passive', max: 5, fuse: 'bugs',
      desc: '丹力流转，生机不绝',
      levels: [ { regen: 0.8, hpPct: 0.06 }, { regen: 1.6, hpPct: 0.12 }, { regen: 2.6, hpPct: 0.18 }, { regen: 3.8, hpPct: 0.25 }, { regen: 5.2, hpPct: 0.33 } ],
      gainText: ['回复+0.8 寿元+6%', '回复+0.8 寿元+6%', '回复+1.2 寿元+6%', '回复+1.4 寿元+8%'] },
    crit:    { name: '太虚剑意', icon: 'icons/swordcraft_xinfa.png', cat: '灵', type: 'passive', max: 5, fuse: 'eye',
      desc: '剑意通玄，招招致命',
      levels: [ { cc: 0.06, cm: 0.15 }, { cc: 0.12, cm: 0.30 }, { cc: 0.18, cm: 0.45 }, { cc: 0.24, cm: 0.62 }, { cc: 0.30, cm: 0.80 } ],
      gainText: ['会心+6% 会伤+15%', '会心+6% 会伤+15%', '会心+6% 会伤+17%', '会心+6% 会伤+18%'] },
    eye:     { name: '天眼通', icon: 'icons/uniquecard_draw.png', cat: '灵', type: 'passive', max: 5, fuse: 'crit',
      desc: '天眼洞悉，破绽尽显',
      levels: [ { cc: 0.04, dodge: 0.04 }, { cc: 0.08, dodge: 0.08 }, { cc: 0.12, dodge: 0.12 }, { cc: 0.16, dodge: 0.17 }, { cc: 0.20, dodge: 0.22 } ],
      gainText: ['会心+4% 闪避+4%', '会心+4% 闪避+4%', '会心+4% 闪避+4%', '会心+4% 闪避+5%'] },
  },

  // ---- 融合产物（超武）----
  // 两个配对技能都满级后自动融合，占 1 个装备栏，效果远超原技能
  fusions: {
    wanjian:    { name: '万剑归宗', icon: 'icons/swordcraft_flying_sword_defend.png', cat: '剑', type: 'active',
      parts: ['sword', 'wave'], desc: '万剑齐发，剑雨遮天',
      data: { cd: 0.9, dmg: 55, swords: 5, speed: 900 } },
    qingzhu:    { name: '青竹诛仙阵', icon: 'icons/array.png', cat: '剑', type: 'active',
      parts: ['bamboo', 'aura'], desc: '青竹剑阵封天锁地',
      data: { blades: 10, dmg: 70, r: 130, spin: 2.6, cd: 2.6, count: 18 } },
    fenlei:     { name: '焚天雷劫', icon: 'icons/spellcraft_lightning_attack.png', cat: '法', type: 'active',
      parts: ['fire', 'thunder'], desc: '雷火交加，焚天灭地',
      data: { cd: 2.6, dmg: 150, r: 150, targets: 8, chain: 4 } },
    bingfeng:   { name: '冰封千里', icon: 'icons/spellcraft_water.png', cat: '法', type: 'active',
      parts: ['ice', 'stone'], desc: '冰峰坠世，千里冰封',
      data: { cd: 3.2, dmg: 110, slow: 0.7, slowT: 4, count: 10 } },
    wanling:    { name: '万灵朝宗', icon: 'icons/avatar_scripture_attack.png', cat: '灵', type: 'summon',
      parts: ['spirit', 'puppet'], desc: '傀儡剑灵，万灵齐攻',
      data: { count: 5, pct: 0.9, cd: 0.5, hp: 260 } },
    chongchao:  { name: '噬灵虫潮', icon: 'icons/bodyforge_qinna.png', cat: '灵', type: 'summon',
      parts: ['bugs', 'pill'], desc: '虫潮遮天，噬尽一切',
      data: { count: 24, dmg: 26, cd: 0.5 } },
    jinzhen:    { name: '不灭金身', icon: 'icons/bodyforge_dianxue.png', cat: '体', type: 'passive',
      parts: ['body', 'parry'], desc: '金身不灭，万法不侵',
      data: { hp: 400, dr: 0.35, reflect: 150, chance: 0.5, regen: 6 } },
    liuguang:   { name: '瞬影流光', icon: 'icons/nimble.png', cat: '体', type: 'passive',
      parts: ['wind', 'blink'], desc: '身化流光，如影随形',
      data: { speedPct: 0.75, dodgeCd: 0.4, invuln: 0.6, distPct: 1.2 } },
    xuechi:     { name: '血噬苍穹', icon: 'icons/vitality_power_word_attack.png', cat: '体', type: 'passive',
      parts: ['devour', 'blood'], desc: '吞噬天地，血煞滔天',
      data: { lifesteal: 0.3, dmgPct: 0.4, xpPct: 0.7, rangePct: 1.8 } },
    shentong:   { name: '破妄神瞳', icon: 'icons/uniquecard_draw.png', cat: '灵', type: 'passive',
      parts: ['crit', 'eye'], desc: '神瞳破妄，必中必暴',
      data: { cc: 0.5, cm: 1.2, dodge: 0.3 } },
  },

  // ---- 灵气珠 ----
  orb: { radius: 7, attractR: 95, attractSpeed: 620, maxCount: 220, healChance: 0.02, healAmt: 10 },
  orbDrop: { normal: 2, elite: 5, boss: 25 },

  // ---- 渲染 ----
  fx: { shake: 1, hitStop: 0.045 },
};
